packages:
  - packages/*
  - submodules/material-viewer/packages/*
  - submodules/three.js

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  puppeteer: true
  sharp: true

link-workspace-packages: false
