packages:
  - packages/*
  - submodules/material-viewer/packages/*
  - submodules/three.js

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  puppeteer: true
  sharp: true

link-workspace-packages: false

minimumReleaseAgeExclude:
  - humanize-units
  - yargs-file-commands
  - tanstack-router-ga4
  - '@vitest/coverage-v8'
  - '@vitest/mocker'
  - '@vitest/spy'
  - vitest
