/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAssetSplatRouteImport } from './routes/api/asset/$'
import { Route as ApiMaterialSourceMaterialTypeMaterialNameRouteImport } from './routes/api/material-source/$materialType/$materialName'
import { Route as ApiReferenceImageMaterialTypeMaterialNameAdapterRouteImport } from './routes/api/reference-image/$materialType/$materialName/$adapter'
import { Route as ApiReferenceReportMaterialTypeMaterialNameAdapterRouteImport } from './routes/api/reference-report/$materialType/$materialName/$adapter'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetSplatRoute = ApiAssetSplatRouteImport.update({
  id: '/api/asset/$',
  path: '/api/asset/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMaterialSourceMaterialTypeMaterialNameRoute =
  ApiMaterialSourceMaterialTypeMaterialNameRouteImport.update({
    id: '/api/material-source/$materialType/$materialName',
    path: '/api/material-source/$materialType/$materialName',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiReferenceImageMaterialTypeMaterialNameAdapterRoute =
  ApiReferenceImageMaterialTypeMaterialNameAdapterRouteImport.update({
    id: '/api/reference-image/$materialType/$materialName/$adapter',
    path: '/api/reference-image/$materialType/$materialName/$adapter',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiReferenceReportMaterialTypeMaterialNameAdapterRoute =
  ApiReferenceReportMaterialTypeMaterialNameAdapterRouteImport.update({
    id: '/api/reference-report/$materialType/$materialName/$adapter',
    path: '/api/reference-report/$materialType/$materialName/$adapter',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/asset/$': typeof ApiAssetSplatRoute
  '/api/material-source/$materialType/$materialName': typeof ApiMaterialSourceMaterialTypeMaterialNameRoute
  '/api/reference-image/$materialType/$materialName/$adapter': typeof ApiReferenceImageMaterialTypeMaterialNameAdapterRoute
  '/api/reference-report/$materialType/$materialName/$adapter': typeof ApiReferenceReportMaterialTypeMaterialNameAdapterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/asset/$': typeof ApiAssetSplatRoute
  '/api/material-source/$materialType/$materialName': typeof ApiMaterialSourceMaterialTypeMaterialNameRoute
  '/api/reference-image/$materialType/$materialName/$adapter': typeof ApiReferenceImageMaterialTypeMaterialNameAdapterRoute
  '/api/reference-report/$materialType/$materialName/$adapter': typeof ApiReferenceReportMaterialTypeMaterialNameAdapterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/asset/$': typeof ApiAssetSplatRoute
  '/api/material-source/$materialType/$materialName': typeof ApiMaterialSourceMaterialTypeMaterialNameRoute
  '/api/reference-image/$materialType/$materialName/$adapter': typeof ApiReferenceImageMaterialTypeMaterialNameAdapterRoute
  '/api/reference-report/$materialType/$materialName/$adapter': typeof ApiReferenceReportMaterialTypeMaterialNameAdapterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/asset/$'
    | '/api/material-source/$materialType/$materialName'
    | '/api/reference-image/$materialType/$materialName/$adapter'
    | '/api/reference-report/$materialType/$materialName/$adapter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/asset/$'
    | '/api/material-source/$materialType/$materialName'
    | '/api/reference-image/$materialType/$materialName/$adapter'
    | '/api/reference-report/$materialType/$materialName/$adapter'
  id:
    | '__root__'
    | '/'
    | '/api/asset/$'
    | '/api/material-source/$materialType/$materialName'
    | '/api/reference-image/$materialType/$materialName/$adapter'
    | '/api/reference-report/$materialType/$materialName/$adapter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAssetSplatRoute: typeof ApiAssetSplatRoute
  ApiMaterialSourceMaterialTypeMaterialNameRoute: typeof ApiMaterialSourceMaterialTypeMaterialNameRoute
  ApiReferenceImageMaterialTypeMaterialNameAdapterRoute: typeof ApiReferenceImageMaterialTypeMaterialNameAdapterRoute
  ApiReferenceReportMaterialTypeMaterialNameAdapterRoute: typeof ApiReferenceReportMaterialTypeMaterialNameAdapterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/asset/$': {
      id: '/api/asset/$'
      path: '/api/asset/$'
      fullPath: '/api/asset/$'
      preLoaderRoute: typeof ApiAssetSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/material-source/$materialType/$materialName': {
      id: '/api/material-source/$materialType/$materialName'
      path: '/api/material-source/$materialType/$materialName'
      fullPath: '/api/material-source/$materialType/$materialName'
      preLoaderRoute: typeof ApiMaterialSourceMaterialTypeMaterialNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reference-image/$materialType/$materialName/$adapter': {
      id: '/api/reference-image/$materialType/$materialName/$adapter'
      path: '/api/reference-image/$materialType/$materialName/$adapter'
      fullPath: '/api/reference-image/$materialType/$materialName/$adapter'
      preLoaderRoute: typeof ApiReferenceImageMaterialTypeMaterialNameAdapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reference-report/$materialType/$materialName/$adapter': {
      id: '/api/reference-report/$materialType/$materialName/$adapter'
      path: '/api/reference-report/$materialType/$materialName/$adapter'
      fullPath: '/api/reference-report/$materialType/$materialName/$adapter'
      preLoaderRoute: typeof ApiReferenceReportMaterialTypeMaterialNameAdapterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAssetSplatRoute: ApiAssetSplatRoute,
  ApiMaterialSourceMaterialTypeMaterialNameRoute:
    ApiMaterialSourceMaterialTypeMaterialNameRoute,
  ApiReferenceImageMaterialTypeMaterialNameAdapterRoute:
    ApiReferenceImageMaterialTypeMaterialNameAdapterRoute,
  ApiReferenceReportMaterialTypeMaterialNameAdapterRoute:
    ApiReferenceReportMaterialTypeMaterialNameAdapterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
