name: Deploy results site to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  deploy:
    name: Deploy results site to Cloud Run
    needs: ci
    uses: ./.github/workflows/deploy-service.yml
    with:
      service_name: material-fidelity
      dockerfile: docker/results.Dockerfile
      context: submodules/mtlx-sample-library/materials
      submodules: viewer
    secrets:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
